### ISSUE TITLE
Migrar repositório para org da SOS

### ISSUE THREAD

**Issue by willMoraes** [emiliosheinz/sos-pet#45]
- Criar repo do SOS com e-mail 
- Criar conta na Vercel

**Comment by emiliosheinz** [comment]
Me recuso a pagar 20 dolares por mes só pra poder fazer deploy de um app na vercel. Fechando a task pois acredito que não vale a pena.

![a49624f6-7731-4901-a3a3-daf8af861d89](https://github.com/emiliosheinz/sos-pet/assets/103655828/ac35d2c4-726a-41bb-91cf-97204fdd4791)
